import{a as L,S as k,i as m}from"./assets/vendor-ee72e1a4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const w=async(e,s=1,o=15)=>{const a=await L.get("https://pixabay.com/api/",{params:{key:"44369714-aeb99d27cdb76d6e65f8cf0da",q:e,image_type:"photo",page:s,per_page:o}});if(a.status!==200)throw new Error(a.status);return a.data},E=(e,s)=>{s.insertAdjacentHTML("beforeend",S(e)),g.refresh()},g=new k(".gallery-link",{captionsData:"alt",captionDelay:250});g.on("error.simplelightbox",function(e){console.log(e)});function S(e){return e.reduce((s,{webformatURL:o,largeImageURL:a,tags:t,likes:r,views:n,comments:h,downloads:b})=>s+=`<li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img
          class="gallery-image"
          src="${o}" 
          alt="${t}"
        />
        <div class="picture-describe">
        <span><span class="title">Likes</span>${r}</span>
        <span><span class="title">Views</span>${n}</span>
        <span><span class="title">Comments</span>${h}</span>
        <span><span class="title">Downloads</span>${b}</span>
        </div>
      </a>
    </li>`,"")}const d=document.querySelector(".gallery"),l=document.createElement("div");l.className="loader";d.appendChild(l);const i=document.querySelector(".load-more"),p=document.getElementById("loading-message");let c=1,u="";const q={position:"topRight",theme:"dark",color:"#ef4040",message:"Sorry, there are no images matching your search query. Please try again!"};document.querySelector("form").addEventListener("submit",async e=>{e.preventDefault(),d.innerHTML="",c=1,u=e.target.searchrequest.value,await f(u),e.target.reset()});i.addEventListener("click",()=>{f(u)});const f=async e=>{l.style.display="flex",i.style.display="none",p.style.display="block";try{const s=await w(e,c);l.style.display="none",p.style.display="none",s.hits.length===0?m.error(q):(E(s.hits,d),c+=1,i.style.display="block"),c>s.totalHits/15&&(i.style.display="none",m.info({position:"topRight",theme:"dark",color:"#007bff",message:"We're sorry, but you've reached the end of search results."}))}catch(s){l.style.display="none",p.style.display="none",d.innerHTML="Something went wrong. <br/>Please, check your connection and try again.",console.error(s)}},y=document.querySelector(".slide");y&&(y.addEventListener("click",e=>{document.body.classList.toggle("black"),document.body.firstElementChild.classList.toggle("black"),document.getElementById("searchrequest").classList.toggle("black"),e.target.firstElementChild.checked=!e.target.firstElementChild.checked}),setTimeout(()=>{y.style.opacity="0.1"},5e3));
//# sourceMappingURL=commonHelpers.js.map
